// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
	Version   int32
	CreatedAt pgtype.Timestamptz
}
