// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Movie struct {
	ID        int64
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
	Version   int32
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
	Version      int32
	CreatedAt    time.Time
}
