// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: movie.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const getMovie = `-- name: GetMovie :one
SELECT id, title, year, runtime, genres, version, created_at
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		pq.Array(&i.Genres),
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
