// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: movie.sql

package db

import (
	"context"
)

const getMovieBy = `-- name: GetMovieBy :one
SELECT id, title, year, runtime, genres, version, created_at
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovieBy(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieBy, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Genres,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
