// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Movie struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Runtime     Runtime   `json:"runtime"`
	Genres      []string  `json:"genres"`
	PublishYear int32     `json:"publish_year"`
	Version     int32     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword []byte    `json:"-"`
	Activated      bool      `json:"activated"`
	Version        int32     `json:"-"`
	CreatedAt      time.Time `json:"created_at"`
}
