// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Movie struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Runtime     Runtime   `json:"runtime"`
	Genres      []string  `json:"genres"`
	PublishYear int32     `json:"publish_year"`
	Version     int32     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
}
