// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies ( title, publish_year, runtime, genres)
VALUES ($1, $2, $3, $4)
RETURNING id, title, runtime, genres, publish_year, version, created_at
`

type CreateMovieParams struct {
	Title       string   `json:"title"`
	PublishYear int32    `json:"publish_year"`
	Runtime     Runtime  `json:"runtime"`
	Genres      []string `json:"genres"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.PublishYear,
		arg.Runtime,
		arg.Genres,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Runtime,
		&i.Genres,
		&i.PublishYear,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :execrows
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovie, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, runtime, genres, publish_year, version, created_at
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Runtime,
		&i.Genres,
		&i.PublishYear,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listMoviesWithFilters = `-- name: ListMoviesWithFilters :many
SELECT id, title, runtime, genres, publish_year, version, created_at
FROM movies
WHERE (to_tsvector('simple', title) @@ plainto_tsquery('simple', $1) OR $1 = '')
AND (genres @> $2 OR $2 = '{}')
ORDER BY CASE
    WHEN NOT $3::boolean AND $4::text = 'id' THEN id
    WHEN NOT $3::boolean AND $4::text = 'publishYear' THEN publish_year
    WHEN NOT $3::boolean AND $4::text = 'runtime' THEN runtime
END ASC, CASE
    WHEN $3::boolean AND $4::text = 'id' THEN id
    WHEN $3::boolean AND $4::text = 'publishYear' THEN publish_year
    WHEN $3::boolean AND $4::text = 'runtime' THEN runtime
END  DESC, CASE
    WHEN NOT $3::boolean AND $4::text = 'title' THEN title
END ASC, CASE
    WHEN $3::boolean AND $4::text = 'title' THEN title
END DESC, id ASC
LIMIT $6 OFFSET $5
`

type ListMoviesWithFiltersParams struct {
	Title   string   `json:"title"`
	Genres  []string `json:"genres"`
	Reverse bool     `json:"reverse"`
	OrderBy string   `json:"order_by"`
	Offset  int32    `json:"offset"`
	Limit   int32    `json:"limit"`
}

func (q *Queries) ListMoviesWithFilters(ctx context.Context, arg ListMoviesWithFiltersParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMoviesWithFilters,
		arg.Title,
		arg.Genres,
		arg.Reverse,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Runtime,
			&i.Genres,
			&i.PublishYear,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET
    title = coalesce($1, title),
    publish_year = coalesce($2, publish_year),
    runtime = coalesce($3::int, runtime),
    genres = coalesce($4, genres),
    version = version + 1
WHERE id = $5 AND version = $6
RETURNING id, title, runtime, genres, publish_year, version, created_at
`

type UpdateMovieParams struct {
	Title       pgtype.Text `json:"title"`
	PublishYear pgtype.Int4 `json:"publish_year"`
	Runtime     pgtype.Int4 `json:"runtime"`
	Genres      []string    `json:"genres"`
	ID          int64       `json:"id"`
	Version     int32       `json:"version"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie,
		arg.Title,
		arg.PublishYear,
		arg.Runtime,
		arg.Genres,
		arg.ID,
		arg.Version,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Runtime,
		&i.Genres,
		&i.PublishYear,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
